<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyTitle>Priv Core Installer</AssemblyTitle>
    <AssemblyCompany>Sans Mercantile</AssemblyCompany>
    <Product>Priv Core Installer</Product>
    <Description>Priv Core Installer for Windows</Description>
    <Version>1.1.0</Version>
    <AssemblyName>Priv Core Installer</AssemblyName>
    <RootNamespace>PrivCoreInstaller</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\PrivCore.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Legal\INSTALLATION_NOTICE.txt" LogicalName="PrivCoreInstaller.Legal.INSTALLATION_NOTICE.txt" />
    <EmbeddedResource Include="Payload\PrivCoreSetupEngine.exe" LogicalName="PrivCoreInstaller.Payload.SetupEngine.exe" />
  </ItemGroup>
</Project>